:navtitle: Introduction
= Introduction

Axon Framework Multitenancy Extension provides your application ability to serve multiple tenants (event-stores) at once. Multi-tenancy is important in cloud computing and this extension will provide ability to connect to tenants dynamically, physical separate tenants data, scale tenants independently...

== Requirements
Currently, following requirements needs to be meet for extension to work:

- Use *Spring Framework* together with *Axon Framework 4.6+*
- Use an event store per tenant. Out of the box this can be Axon Server EE 4.6+ or Axon Cloud. When Axon Server is disabled, the extension can create local tenant segments backed by Axon's `EventStorageEngine`/`EmbeddedEventStore`.
- This is not hard requirement but if you wish to enable multitenancy on projection side, only SQL databases are supported out-of-the box

== Restrictions

Only components that interact with Axon Server or database via JPA are supported out of the box. If you wish to use other components, you need to implement multi-tenancy support for them.

When Axon Server is disabled, tenant discovery is static unless you provide a custom `TenantProvider`. AMQP can be used to forward events and Spring Cloud can be used for command distribution, but neither replaces the event store.
